apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: abentalebali
spec:
  clusterIP: None  # Makes this a headless service
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
